#!/usr/bin/env zsh

#   ██            ████
#  ░░            ░██░
#   ██ ███████  ██████  ██████
#  ░██░░██░░░██░░░██░  ██░░░░██
#  ░██ ░██  ░██  ░██  ░██   ░██
#  ░██ ░██  ░██  ░██  ░██   ░██
#  ░██ ███  ░██  ░██  ░░██████
#  ░░ ░░░   ░░   ░░    ░░░░░░
#
# info by N. Escobar (https://github.com/nickesc)
#                    (https://github.com/nickesc/.dotfiles)
#                    (https://nickesc.github.io)
#                    (https://nickesc.com)
#
# Usage: info [page|help|all]

footer(){
    printf "\nFor more information, type:    info [page]\nPages:\n"
    \ls "$DOTFILES"/notes
    printf "\n"
}

if [ $# -eq 0 ] || [ "$1" = "help" ]; then
    cat "$DOTFILES"/notes/main | less -e
    cat "$DOTFILES"/notes/main
    footer
elif [ "$1" = "all" ]; then
    cat "$DOTFILES"/notes/* | less -e
    cat "$DOTFILES"/notes/*
    footer
elif [ -f "$DOTFILES/notes/$1" ]; then
    cat "$DOTFILES/notes/$1" | less -e
    cat "$DOTFILES/notes/$1"
    footer
else
    echo ""
    echo "No info page found."
    footer
fi
