#!/usr/bin/env zsh

# Update App Store apps
sudo softwareupdate -i -a

# Update Homebrew (Cask) & packages
brew update
brew upgrade
brew cleanup
brew doctor
brew cu --yes
# brew cu --all --yes

# Update npm & packages
npm install npm -g
npm update -g

# Update Ruby & gems
sudo gem update -system
sudo gem update
sudo gem cleanup


## Node.js, npm, npx, yarn
#Update n
n-update -y

## Python, pyenv, pip
python -m pip install --upgrade pip
python2 -m pip install --upgrade pip

pyenv rehash

# update fnt font manager catalogue
fnt update


